"""Initial full baseline

Revision ID: 6d0e3571139f
Revises: 
Create Date: 2026-04-14 08:10:23.291614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database


# revision identifiers, used by Alembic.
revision: str = '6d0e3571139f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_states')),
    sa.UniqueConstraint('code', name=op.f('uq_states_code')),
    sa.UniqueConstraint('name', name=op.f('uq_states_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('NATIONAL_ADMIN', 'STATE_COORDINATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_data_source'), 'documents', ['data_source'], unique=False)
    op.create_index(op.f('ix_documents_state'), 'documents', ['state'], unique=False)
    op.create_table('lgas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_lgas_state_id_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lgas'))
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_ref_id'), 'projects', ['ref_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=300), nullable=False),
    sa.Column('commodity', app.database.PG_JSON(), nullable=False),
    sa.Column('fy_awarded', sa.Integer(), nullable=True),
    sa.Column('fy_completed', sa.Integer(), nullable=True),
    sa.Column('programme_phase', sa.String(length=50), nullable=True),
    sa.Column('fiscal_quarter', sa.String(length=10), nullable=True),
    sa.Column('vcdp_component', app.database.PG_JSON(), nullable=False),
    sa.Column('vcdp_sub_components', app.database.PG_JSON(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('lgas', app.database.PG_JSON(), nullable=False),
    sa.Column('threeFS_primary', app.database.PG_JSON(), nullable=False),
    sa.Column('threeFS_sub_components', app.database.PG_JSON(), nullable=False),
    sa.Column('cofog_code', sa.String(length=50), nullable=True),
    sa.Column('funding_sources', app.database.PG_JSON(), nullable=False),
    sa.Column('sub_funding_sources', app.database.PG_JSON(), nullable=False),
    sa.Column('expenditure_fgn', sa.Float(), nullable=False),
    sa.Column('expenditure_state', sa.Float(), nullable=False),
    sa.Column('expenditure_ifad', sa.Float(), nullable=False),
    sa.Column('expenditure_oof', sa.Float(), nullable=False),
    sa.Column('expenditure_beneficiary', sa.Float(), nullable=False),
    sa.Column('expenditure_other', sa.Float(), nullable=False),
    sa.Column('expenditure_total', sa.Float(), nullable=False),
    sa.Column('expenditure_total_reported', sa.Float(), nullable=False),
    sa.Column('beneficiary_categories', app.database.PG_JSON(), nullable=False),
    sa.Column('beneficiary_total', sa.Integer(), nullable=True),
    sa.Column('beneficiary_male', sa.Integer(), nullable=True),
    sa.Column('beneficiary_female', sa.Integer(), nullable=True),
    sa.Column('beneficiary_youth_under35', sa.Integer(), nullable=True),
    sa.Column('beneficiary_male_percentage', sa.Float(), nullable=True),
    sa.Column('beneficiary_female_percentage', sa.Float(), nullable=True),
    sa.Column('beneficiary_youth_percentage', sa.Float(), nullable=True),
    sa.Column('beneficiary_plwd', sa.Integer(), nullable=True),
    sa.Column('value_chain_segments', app.database.PG_JSON(), nullable=False),
    sa.Column('climate_flag', sa.String(length=5), nullable=True),
    sa.Column('data_source', app.database.PG_JSON(), nullable=True),
    sa.Column('supporting_documents', app.database.PG_JSON(), nullable=False),
    sa.Column('entered_by', sa.String(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('classification_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REJECTED', 'DRAFT', 'PUBLISHED', name='transactionstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], name=op.f('fk_transactions_entered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_ref_id'), 'transactions', ['ref_id'], unique=True)
    op.create_index(op.f('ix_transactions_state'), 'transactions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_state'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ref_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_projects_ref_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('lgas')
    op.drop_index(op.f('ix_documents_state'), table_name='documents')
    op.drop_index(op.f('ix_documents_data_source'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('states')
    # ### end Alembic commands ###
